apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
  labels:
    service: redis
spec:
  selector:
    service: redis
    redis: master
  clusterIP: None
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
