apiVersion: v1
kind: Service
metadata:
  name: redis-slave-service
  labels:
    service: redis
spec:
  selector:
    service: redis
    redis: slave
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6378
      targetPort: 6379
