apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: emailapp-vpa
  labels:
    service: email
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emailapp-deployment
  updatePolicy:
    updateMode: "Off"
