version: '3'
services:
  db:
    image: mysql:8.0.31
    container_name: db
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=myapp
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ticketsApp
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flaskApp
    ports:
      - '5000:5000'
    networks:
      - ticketsApp
    depends_on:
      - db
    environment:
      - FLASK_ENV=prod
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=myapp
      - SECRET_KEY="secret_key"
networks:
  ticketsApp:
volumes:
  dbdata:
