version: '3'
services:
  db:
    image: mysql:8.0.31
    container_name: db
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=myapp
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ticketsApp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: tickets-app
    container_name: flaskApp
    ports:
      - '5000:5000'
    networks:
      - ticketsApp
    depends_on:
      - db
    environment:
      - FLASK_ENV=prod
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=myapp
      - SECRET_KEY="secret_key"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      test: ["CMD-SHELL", "curl -f http://localhost:5000/users/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  ticketsApp:
volumes:
  dbdata:
