apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    service: redis
data:
  master_url: "redis-master-service.default.svc.cluster.local"
  slave_url: "redis-slave-service.default.svc.cluster.local"
  master_port: "6379"
  slave_port: "6378"
  redis.conf: |-

    save 60 1
    loglevel warning
    bind 0.0.0.0
    protected-mode no
