apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mysql-vpa
  labels:
    service: app
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mysql-statefulset
  updatePolicy:
    updateMode: "Off"
