"""empty message

Revision ID: 22a35b666514
Revises: b02eb2007439
Create Date: 2023-06-16 05:58:59.265914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a35b666514'
down_revision = 'b02eb2007439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('u_username', ['u_username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('u_username', type_='unique')

    # ### end Alembic commands ###
