"""empty message

Revision ID: 35e8f627c53b
Revises: b3710da1993f
Create Date: 2023-06-14 23:28:25.484394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e8f627c53b'
down_revision = 'b3710da1993f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('b_name', sa.String(length=20), nullable=True),
    sa.Column('b_status', sa.Enum('live', 'not_live'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    op.drop_table('branch')
    # ### end Alembic commands ###
