"""create user table

Revision ID: 540ba981cdaf
Revises: 
Create Date: 2023-06-13 21:47:01.020034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540ba981cdaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
