"""empty message

Revision ID: b02eb2007439
Revises: cff86a14c623
Create Date: 2023-06-15 07:18:57.141117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02eb2007439'
down_revision = 'cff86a14c623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('u_username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('u_password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('u_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('u_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('u_password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('u_username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
