"""empty message

Revision ID: b3710da1993f
Revises: fa1503119443
Create Date: 2023-06-14 23:25:14.764536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3710da1993f'
down_revision = 'fa1503119443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_code', sa.String(length=20), nullable=False),
    sa.Column('t_description', sa.String(length=100), nullable=True),
    sa.Column('t_status', sa.Enum('pending', 'ongoing', 'done'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('t_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
