"""empty message

Revision ID: cff86a14c623
Revises: 35e8f627c53b
Create Date: 2023-06-15 07:15:48.953782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff86a14c623'
down_revision = '35e8f627c53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('u_password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('u_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('u_secret', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'inactive'), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('u_secret')
        batch_op.drop_column('u_name')
        batch_op.drop_column('u_password')
        batch_op.drop_column('u_username')

    # ### end Alembic commands ###
