"""create_ticket_table

Revision ID: fe5375e1bd86
Revises: 
Create Date: 2023-07-04 08:52:51.841338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5375e1bd86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('t_code', sa.Integer(), nullable=False),
    sa.Column('t_description', sa.String(length=100), nullable=True),
    sa.Column('t_status', sa.Enum('pending', 'ongoing', 'done', name='ticketstatus'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_username', sa.String(length=50), nullable=False),
    sa.Column('u_password', sa.String(length=200), nullable=False),
    sa.Column('u_name', sa.String(length=50), nullable=False),
    sa.Column('u_secret', sa.String(length=15), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_username')
    )
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('b_name', sa.String(length=20), nullable=True),
    sa.Column('b_status', sa.Enum('live', 'not_live', name='branchstatus'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch')
    op.drop_table('user')
    op.drop_table('ticket')
    # ### end Alembic commands ###
