apiVersion: v1
kind: Service
metadata:
  name: ticketsapp-service
  labels:
    service: app
spec:
  selector:
    service: app
    app: ticketsapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
