apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-master-vpa
  labels:
    service: redis
    redis: master
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis-master-statefulset
  updatePolicy:
    updateMode: "Off"
