apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-slave-hpa
  labels:
    service: redis
    redis: slave
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis-slave-statefulset
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
