apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailapp-deployment
  labels:
    service: email
spec:
  selector:
    matchLabels:
      service: email
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: email
    spec:
      initContainers:
        - name: init-queue
          image: busybox
          imagePullPolicy: IfNotPresent
          env:
            - name: QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: slave_url
          command: ['sh', '-c', "until nslookup $(QUEUE_HOST); do echo waiting for master server; sleep 2; done"]
      containers:
        - name: emailapp
          image: abir10101/email-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SENDER_EMAIL_NAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email
            - name: SENDER_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email_password
            - name: QUEUE_MASTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: master_url
            - name: QUEUE_MASTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: master_port
            - name: QUEUE_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: QUEUE_SLAVE_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: slave_url
            - name: QUEUE_SLAVE_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: slave_port
            - name: QUEUE_SLAVE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "300m"
              memory: "100Mi"
      imagePullSecrets:
        - name: docker-registry-secret
