apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  labels:
    service: all
provisioner: rancher.io/local-path
parameters:
  type: pd-ssd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
