name: Merge to Develop on Main Push

on:
  push:
    branches:
      - main

jobs:
  merge_to_develop:
    runs-on: test-runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.email "abirmoulick998@gmail.com"
          git config --global user.name "github action" 

      - name: Merge to Develop Branch
        run: |
          git fetch origin develop
          git checkout develop
          git pull origin main

      - name: Push Changes to Develop
        run: |
          git push origin develop
