name: Merge to Develop on Main Push

on:
  push:
    branches:
      - main

jobs:
  merge_to_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge to Develop Branch
        run: |
          git fetch origin develop
          git checkout develop
          git merge --allow-unrelated-histories --no-ff ${{ github.event.after }}

      - name: Push Changes to Develop
        run: |
          git push origin develop
