name: Merge to Develop on Main Push

on:
  push:
    branches:
      - main

jobs:
  merge_to_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.email "abirmoulick998@gmail.com"
          git config --global user.name "github action" 

      - name: Fetch and Checkout Develop Branch
        run: |
          git fetch origin develop
          git checkout develop

      - name: Attempt Merge
        run: |
          git merge --allow-unrelated-histories --no-ff ${{ github.event.after }} || true

      - name: Resolve Merge Conflicts If Necessary
        run: |
          conflicted_files=$(git diff --name-only --diff-filter=U)
          if [ -n "$conflicted_files" ]; then
            for file in $conflicted_files; do
              git checkout --theirs "$file"
              git add "$file"
            done
            git commit -m "Resolved merge conflicts by choosing develop branch changes"
          fi

      - name: Push Changes to Develop
        run: |
          git push origin develop
