name: Unit Testing

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: test-runner
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r appService/requirements.txt
        export FLASK_ENV="test"
    - name: test application
      run: |
        pytest appService/tests
