name: unitTesting

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  test:
    runs-on: test-runner
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r appService/requirements.txt
        export FLASK_ENV="test"
    - name: test application
      run: |
        pytest appService/tests
