name: Unit Testing 

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: test-runner
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m venv env && source env/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r appService/requirements.txt
    - name: test application
      run: |
        export FLASK_ENV="test"
        pytest appService/tests
